version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - 20080:80
      - 20043:443
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
    restart: always

  fpm:
    build: ./php
    volumes:
      - ./html:/var/www/html
      - ./php/log:/var/log/php-fpm
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
    command: ["supervisord", "-n"]
    restart: always

  mysql:
    build: ./mysql
    ports:
      - 20081:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drawQPAL
      MYSQL_DATABASE: draw
      MYSQL_USER: draw
      MYSQL_PASSWORD: drawQPAL
    restart: always

  redis:
    build: ./redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: ["redis-server", "--requirepass", "drawQPAL"]
    restart: always

  xunsearch:
    build: ./xunsearch
    image: ctc/xunsearch:latest
    container_name: ctc-xunsearch
    expose:
      - 8383
      - 8384
    volumes:
      - ./xunsearch/data:/usr/local/xunsearch/data
    restart: always
